import os
import json
import re
from openai import OpenAI

def derive_shipment_context(relative_path: str) -> dict:
    """
    Analyzes the parent folder name to extract two key anchors:
    1. Company Ref (e.g., 2604DSI2798)
    2. Shipping Order / BA Number (e.g., BA3161)
    """
    # Normalize path separators and grab the top parent directory
    parts = relative_path.replace('\\', '/').split('/')
    parent_folder = parts[0] if parts else relative_path
    
    # Defaults in case patterns are missing
    context = {
        "company_ref": "NOT_FOUND",
        "shipping_order": "NOT_FOUND",
        "folder_raw": parent_folder
    }
    
    # 1. Look for the Shipping Order Number (BA followed by numbers, e.g., BA3161)
    ba_match = re.search(r'(BA\d+)', parent_folder, re.IGNORECASE)
    if ba_match:
        context["shipping_order"] = ba_match.group(1).upper()
        
    # 2. Look for the Company Reference (usually starts with numbers like 2602DS... or 2604DS...)
    # This pattern matches any alphanumeric string starting with numbers followed by letters/digits
    ref_match = re.search(r'(\d+[A-Z\d]+DS[A-Z\d]+)', parent_folder, re.IGNORECASE)
    if ref_match:
        context["company_ref"] = ref_match.group(1).upper()
    else:
        # Fallback regex if the reference pattern shifts slightly (e.g., matching the first segment before a hyphen)
        fallback_match = re.search(r'^([A-Z0-9]{8,12})', parent_folder, re.IGNORECASE)
        if fallback_match and not fallback_match.group(1).startswith("BA"):
            context["company_ref"] = fallback_match.group(1).upper()

    return context

def query_local_rag_fields(client, file_name: str, relative_path: str, raw_text: str) -> dict:
    """
    Queries the local SLM, dynamically anchoring the prompt with the extracted
    Company Reference and Shipping Order Number derived from the current path context.
    """
    # Dynamically extract context markers from the folder path
    ctx = derive_shipment_context(relative_path)
    
    # Build anchor hints to guide the 1.5B model's attention window
    hint_str = f"Company Reference: '{ctx['company_ref']}' and Shipping Order: '{ctx['shipping_order']}'"

    prompt = f"""
Analyze the text from document '{file_name}'. Find and extract the logistical metadata parameters requested below.
Focus closely on identifying references and data linked to this shipment context: {hint_str}.

Return ONLY a valid, plain JSON object. Do not wrap the response in markdown formatting codeblocks (such as ```json), notes, or introductions.

[DATA EXTRACTION EXPECTED TEMPLATE SCHEMA]
{{
    "Client Ref": "Find the primary shipment reference matching or related to {ctx['shipping_order']} or {ctx['company_ref']}",
    "Consignee": "Find the importer company or enterprise name, e.g., KAMOA COPPER SA",
    "Description": "Find heavy machinery equipment models, e.g., ELPHINSTONE MOTOR GRADER or CAT EXC",
    "PIN No": "Find the vehicle PIN tracking code, usually starting with CAT...",
    "Serial No": "Find the frame, chassis, or component serial markers",
    "Vessel": "Identify the ocean shipping carrier if named explicitly, otherwise leave blank",
    "Voy": "Identify the voyage routing identifier sequence code, otherwise leave blank",
    "Tariff Code": "Extract the specific custom tariff classification code, e.g., 8429.20"
}}

[DOCUMENT CONTENT FOR ANALYSIS]:
{raw_text[:7000]}
"""

    try:
        response = client.chat.completions.create(
            model="qwen2.5-1.5b-instruct",
            messages=[
                {"role": "system", "content": "You are a strict data extraction engine. Output only raw JSON strings. Do not chat, explain, or output markdown wrappers."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.0,  # Zero temperature forces hard factual alignment
            max_tokens=500
        )
        
        raw_output = response.choices[0].message.content.strip()
        
        # Strip out any potential markdown codeblocks if generated by the model
        clean_json_str = re.sub(r"```json|```", "", raw_output).strip()
        return json.loads(clean_json_str)
        
    except json.JSONDecodeError:
        print(f"   [Warning] Model failed string validation for {file_name}. Continuing...")
        return {}
    except Exception as e:
        print(f"   [Error] Extraction exception on file {file_name}: {e}")
        return {}

def extract_metadata_from_rag():
    client = OpenAI(base_url="http://localhost:8000/v1", api_key="local-no-key")
    
    try:
        with open("rag_database.json", "r", encoding="utf-8") as f:
            rag_db = json.load(f)
    except FileNotFoundError:
        print("[Fatal Error] 'rag_database.json' not found. Run Script 1 first to index target directory paths.")
        return

    extracted_profiles = {}

    print("Beginning contextual metadata extraction from local RAG store...")
    for rel_path, doc_data in rag_db.items():
        if doc_data["status"] == "SUCCESS":
            # Extract current keys to populate clean dashboard tracking prints
            ctx = derive_shipment_context(rel_path)
            print(f" -> [{ctx['shipping_order']} / {ctx['company_ref']}] Extracting fields from: {rel_path}")
            
            metadata = query_local_rag_fields(client, doc_data["file_name"], rel_path, doc_data["raw_text"])
            if metadata:
                extracted_profiles[rel_path] = metadata
        else:
            print(f" -> Skipping file: {rel_path} (Status flag: {doc_data['status']})")

    # Save to file for Script 3 to pick up
    with open("structured_metadata.json", "w", encoding="utf-8") as f:
        json.dump(extracted_profiles, f, indent=4, ensure_ascii=False)
        
    print(f"\nSuccess! Extracted profiles saved to 'structured_metadata.json'")

if __name__ == "__main__":
    extract_metadata_from_rag()