import json
import re
from openai import OpenAI

def query_local_rag_fields(client, file_name: str, raw_text: str) -> dict:
    """Queries the local SLM to gather exact metadata items from document streams."""
    prompt = f"""
Analyze the extracted document text for file '{file_name}'. Extract the exact metadata variables requested below.
Return ONLY a valid, plain JSON object. Do not wrap the response in markdown codeblocks (such as ```json), notes, or descriptive text.

Target JSON Data Layout Object:
{{
    "Client Ref": "Look for matching transaction reference tokens like 2602DS12783 or BA3087",
    "Consignee": "Look for the target importer company or business name, e.g., KAMOA COPPER SA",
    "Description": "Look for equipment models or industrial goods labels, e.g., ELPHINSTONE MOTOR GRADER",
    "PIN No": "Look for unique vehicle PIN identifiers, often starting with CAT...",
    "Serial No": "Look for the vehicle frame, chassis, or equipment component serial markers",
    "Vessel": "Identify the ocean shipping carrier if named, e.g., TRANCURA",
    "Voy": "Identify the tracking sea voyage sequence number, e.g., 612S",
    "Tariff Code": "Extract the specific custom tariff classification code, e.g., 8429.20"
}}

Document Text Segment:
{raw_text[:6000]}
"""
    try:
        response = client.chat.completions.create(
            model="qwen2.5-1.5b-instruct",
            messages=[
                {"role": "system", "content": "You are a rigid data utility. Output only strict JSON strings. Do not chat or add explanations."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.0,
            max_tokens=450
        )
        # Strip codeblock wrappers if generated by the model despite instructions
        clean_json = re.sub(r"```json|```", "", response.choices[0].message.content).strip()
        return json.loads(clean_json)
    except Exception as e:
        print(f"   Extraction failure on file {file_name}: {e}")
        return {}

def extract_metadata_from_rag():
    client = OpenAI(base_url="http://localhost:8000/v1", api_key="local-no-key")
    
    with open("rag_database.json", "r", encoding="utf-8") as f:
        rag_db = json.load(f)

    extracted_profiles = {}

    for rel_path, doc_data in rag_db.items():
        if doc_data["status"] == "SUCCESS":
            print(f"Querying local RAG for data elements inside: {rel_path}")
            metadata = query_local_rag_fields(client, doc_data["file_name"], doc_data["raw_text"])
            if metadata:
                extracted_profiles[rel_path] = metadata
        else:
            print(f"Skipping file: {rel_path} (Status flag: {doc_data['status']})")

    with open("structured_metadata.json", "w", encoding="utf-8") as f:
        json.dump(extracted_profiles, f, indent=4, ensure_ascii=False)
    print("\nMetadata processing complete. Results committed to 'structured_metadata.json'.")

if __name__ == "__main__":
    extract_metadata_from_rag()